### ISSUE TITLE
Step 5 not working

### ISSUE THREAD

**Issue by YufusKhan** [yufeikang/raycast_api_proxy#3]
`yusuf@Yusufs-iMac raycast_api_proxy % python ./app/main.py
Traceback (most recent call last):
  File "/Users/yusuf/raycast_api_proxy/./app/main.py", line 6, in <module>
    import httpx
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/httpx/__init__.py", line 2, in <module>
    from ._api import delete, get, head, options, patch, post, put, request, stream
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/httpx/_api.py", line 4, in <module>
    from ._client import Client
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/httpx/_client.py", line 10, in <module>
    from ._auth import Auth, BasicAuth, FunctionAuth
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/httpx/_auth.py", line 8, in <module>
    from urllib.request import parse_http_list
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 88, in <module>
    import http.client
  File "/Users/yusuf/raycast_api_proxy/app/http.py", line 6, in <module>
    from fastapi import HTTPException
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/fastapi/__init__.py", line 7, in <module>
    from .applications import FastAPI as FastAPI
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/fastapi/applications.py", line 16, in <module>
    from fastapi import routing
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/fastapi/routing.py", line 32, in <module>
    from fastapi.dependencies.models import Dependant
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/fastapi/dependencies/models.py", line 4, in <module>
    from fastapi.security.base import SecurityBase
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/fastapi/security/__init__.py", line 1, in <module>
    from .api_key import APIKeyCookie as APIKeyCookie
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/fastapi/security/api_key.py", line 6, in <module>
    from starlette.requests import Request
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/starlette/requests.py", line 3, in <module>
    from http import cookies as http_cookies
ImportError: cannot import name 'cookies' from partially initialized module 'http' (most likely due to a circular import) (/Users/yusuf/raycast_api_proxy/app/http.py)`

**Comment by yufeikang** [comment]
please retry !
