### ISSUE TITLE
Sync features

### ISSUE THREAD

**Issue by Erik262** [yufeikang/raycast_api_proxy#34]
Are there any plans to implement synchronization features?

**Comment by littleblack111** [comment]
I added that in #29 ?

**Comment by Erik262** [comment]
weird, there are a lot of errors when I try to turn it on.

**Comment by littleblack111** [comment]
> weird, there are a lot of errors when I try to turn it on.

what are them? pls provide log from server and show me the error in client

**Comment by Erik262** [comment]
> > weird, there are a lot of errors when I try to turn it on.
> 
> what are them? pls provide log from server and show me the error in client

Sure, but this happens immediately after turning on cloud sync. Here is a snippet of it (error repeats about three times):

`ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/project/pkgs/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/project/pkgs/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/project/pkgs/fastapi/applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "/project/pkgs/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/project/pkgs/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/project/pkgs/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/project/pkgs/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/project/pkgs/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/project/pkgs/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/project/pkgs/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/project/pkgs/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/project/pkgs/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/project/pkgs/starlette/routing.py", line 69, in app
    await response(scope, receive, send)
  File "/project/pkgs/starlette/responses.py", line 164, in __call__
    await send(
  File "/project/pkgs/starlette/middleware/exceptions.py", line 65, in sender
    await send(message)
  File "/project/pkgs/starlette/middleware/errors.py", line 159, in _send
    await send(message)
  File "/project/pkgs/uvicorn/protocols/http/h11_impl.py", line 509, in send
    event = h11.Response(
  File "/project/pkgs/h11/_events.py", line 166, in __init__
    self.__post_init__()
  File "/project/pkgs/h11/_events.py", line 249, in __post_init__
    raise LocalProtocolError(
h11._util.LocalProtocolError: Response status_code should be in range [200, 1000), not 101
WARNING:  Unsupported upgrade request.
WARNING:  No supported WebSocket library detected. Please use "pip install 'uvicorn[standard]'", or install 'websockets' or 'wsproto' manually.
INFO:proxy:Received request: GET cable
INFO:proxy:Received request: GET https://backend.raycast.com/cable
INFO:     192.168.178.13:57023 - "GET /cable HTTP/1.1" 101 Switching Protocols
ERROR:    Exception in ASGI application`
