### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ammondu** [yufeikang/raycast_api_proxy#35]
2024-06-12 16:55:39 INFO:     Started server process [7]
2024-06-12 16:55:39 INFO:     Waiting for application startup.
2024-06-12 16:55:39 INFO:     Application startup complete.
2024-06-12 16:55:39 INFO:     Uvicorn running on https://0.0.0.0:443 (Press CTRL+C to quit)
2024-06-12 16:56:05 INFO:proxy:Received request to /api/v1/me
2024-06-12 16:56:05 INFO:proxy:Received request: GET https://backend.raycast.com/api/v1/me
2024-06-12 16:56:05 INFO:proxy:Received request to /api/v1/ai/models
2024-06-12 16:56:05 INFO:proxy:Received request: GET https://backend.raycast.com/api/v1/ai/models
2024-06-12 16:56:27 INFO:proxy:Received request: GET api/v1/currencies/crypto
2024-06-12 16:56:27 INFO:proxy:Received request: GET https://backend.raycast.com/api/v1/currencies/crypto?symbols=ADA,AVAX,BCH,BNB,BSV,BTC,DASH,DOGE,DOT,EOS,ETC,ETH,LTC,LUNA,MATIC,NEO,SHIB,SOL,TRX,USDT,XLM,XMR,XRP
2024-06-12 16:56:27 INFO:proxy:Received request: GET api/v1/currencies
2024-06-12 16:56:27 INFO:proxy:Received request: GET https://backend.raycast.com/api/v1/currencies
2024-06-12 16:56:27 INFO:proxy:Received request: GET api/v1/me/trial_status
2024-06-12 16:56:27 INFO:proxy:Received request: GET https://backend.raycast.com/api/v1/me/trial_status
2024-06-12 16:56:27 INFO:proxy:Received request to /api/v1/me
2024-06-12 16:56:27 INFO:proxy:Received request: GET https://backend.raycast.com/api/v1/me
2024-06-12 16:56:27 INFO:proxy:Received request to /api/v1/me
2024-06-12 16:56:27 INFO:proxy:Received request: GET https://backend.raycast.com/api/v1/me
2024-06-12 16:56:27 INFO:proxy:Received request to /api/v1/ai/models
2024-06-12 16:56:27 INFO:proxy:Received request: GET https://backend.raycast.com/api/v1/ai/models
2024-06-12 16:56:39 INFO:proxy:Received request: GET api/v1/currencies/crypto
2024-06-12 16:56:39 INFO:proxy:Received request: GET https://backend.raycast.com/api/v1/currencies/crypto?symbols=ADA,AVAX,BCH,BNB,BSV,BTC,DASH,DOGE,DOT,EOS,ETC,ETH,LTC,LUNA,MATIC,NEO,SHIB,SOL,TRX,USDT,XLM,XMR,XRP
2024-06-12 16:56:39 INFO:proxy:Received request: GET api/v1/currencies
2024-06-12 16:56:39 INFO:proxy:Received request: GET https://backend.raycast.com/api/v1/currencies
2024-06-12 16:56:42 ERROR:    Exception in ASGI application
2024-06-12 16:56:42 Traceback (most recent call last):
2024-06-12 16:56:42   File "/project/app/main.py", line 533, in proxy_translations
2024-06-12 16:56:42     async for content in _get_bot(model_name).translate_completions(
2024-06-12 16:56:42   File "/project/app/main.py", line 471, in _get_bot
2024-06-12 16:56:42     return next(iter(MODELS_DICT.values()))
2024-06-12 16:56:42 StopIteration
2024-06-12 16:56:42 
2024-06-12 16:56:42 The above exception was the direct cause of the following exception:
2024-06-12 16:56:42 
2024-06-12 16:56:42 Traceback (most recent call last):
2024-06-12 16:56:42   File "/project/pkgs/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
2024-06-12 16:56:42     result = await app(  # type: ignore[func-returns-value]
2024-06-12 16:56:42   File "/project/pkgs/uvicorn/middleware/proxy_headers.py", line 78, in __call__
2024-06-12 16:56:42     return await self.app(scope, receive, send)
2024-06-12 16:56:42   File "/project/pkgs/fastapi/applications.py", line 276, in __call__
2024-06-12 16:56:42     await super().__call__(scope, receive, send)
2024-06-12 16:56:42   File "/project/pkgs/starlette/applications.py", line 122, in __call__
2024-06-12 16:56:42     await self.middleware_stack(scope, receive, send)
2024-06-12 16:56:42   File "/project/pkgs/starlette/middleware/errors.py", line 184, in __call__
2024-06-12 16:56:42     raise exc
2024-06-12 16:56:42   File "/project/pkgs/starlette/middleware/errors.py", line 162, in __call__
2024-06-12 16:56:42     await self.app(scope, receive, _send)
2024-06-12 16:56:42   File "/project/pkgs/starlette/middleware/exceptions.py", line 79, in __call__
2024-06-12 16:56:42     raise exc
2024-06-12 16:56:42   File "/project/pkgs/starlette/middleware/exceptions.py", line 68, in __call__
2024-06-12 16:56:42     await self.app(scope, receive, sender)
2024-06-12 16:56:42   File "/project/pkgs/fastapi/middleware/asyncexitstack.py", line 21, in __call__
2024-06-12 16:56:42     raise e
2024-06-12 16:56:42   File "/project/pkgs/fastapi/middleware/asyncexitstack.py", line 18, in __call__
2024-06-12 16:56:42     await self.app(scope, receive, send)
2024-06-12 16:56:42   File "/project/pkgs/starlette/routing.py", line 718, in __call__
2024-06-12 16:56:42     await route.handle(scope, receive, send)
2024-06-12 16:56:42   File "/project/pkgs/starlette/routing.py", line 276, in handle
2024-06-12 16:56:42     await self.app(scope, receive, send)
2024-06-12 16:56:42   File "/project/pkgs/starlette/routing.py", line 66, in app
2024-06-12 16:56:42     response = await func(request)
2024-06-12 16:56:42   File "/project/pkgs/fastapi/routing.py", line 237, in app
2024-06-12 16:56:42     raw_response = await run_endpoint_function(
2024-06-12 16:56:42   File "/project/pkgs/fastapi/routing.py", line 163, in run_endpoint_function
2024-06-12 16:56:42     return await dependant.call(**values)
2024-06-12 16:56:42 RuntimeError: coroutine raised StopIteration
2024-06-12 16:55:37 run uvicorn with ssl
2024-06-12 16:56:37 INFO:     192.168.65.1:61902 - "GET /api/v1/currencies/crypto?symbols=ADA,AVAX,BCH,BNB,BSV,BTC,DASH,DOGE,DOT,EOS,ETC,ETH,LTC,LUNA,MATIC,NEO,SHIB,SOL,TRX,USDT,XLM,XMR,XRP HTTP/1.1" 500 Internal Server Error
2024-06-12 16:56:37 INFO:     192.168.65.1:61903 - "GET /api/v1/currencies HTTP/1.1" 500 Internal Server Error
2024-06-12 16:56:37 INFO:     192.168.65.1:61905 - "GET /api/v1/me/trial_status HTTP/1.1" 500 Internal Server Error
2024-06-12 16:56:37 INFO:     192.168.65.1:61907 - "GET /api/v1/me HTTP/1.1" 500 Internal Server Error
2024-06-12 16:56:37 INFO:     192.168.65.1:61908 - "GET /api/v1/ai/models HTTP/1.1" 500 Internal Server Error
2024-06-12 16:56:42 INFO:     192.168.65.1:61909 - "POST /api/v1/translations HTTP/1.1" 500 Internal Server Error
2024-06-12 16:56:49 INFO:     192.168.65.1:61902 - "GET /api/v1/currencies/crypto?symbols=ADA,AVAX,BCH,BNB,BSV,BTC,DASH,DOGE,DOT,EOS,ETC,ETH,LTC,LUNA,MATIC,NEO,SHIB,SOL,TRX,USDT,XLM,XMR,XRP HTTP/1.1" 500 Internal Server Error
2024-06-12 16:56:49 INFO:     192.168.65.1:61903 - "GET /api/v1/currencies HTTP/1.1" 500 Internal Server Error
2024-06-12 16:58:22 run uvicorn with ssl
2024-06-12 16:58:22 Config file not found at path: custom_mapping.yml
2024-06-12 16:58:22 INFO:     Started server process [8]
2024-06-12 16:58:22 INFO:     Waiting for application startup.
2024-06-12 16:58:22 INFO:     Application startup complete.
2024-06-12 16:58:22 INFO:     Uvicorn running on https://0.0.0.0:443 (Press CTRL+C to quit)
2024-06-12 16:58:30 INFO:proxy:Received request to /api/v1/me
2024-06-12 16:58:30 INFO:proxy:Received request: GET https://backend.raycast.com/api/v1/me
2024-06-12 16:58:30 INFO:proxy:Received request to /api/v1/ai/models
2024-06-12 16:58:30 INFO:proxy:Received request: GET https://backend.raycast.com/api/v1/ai/models
2024-06-12 16:58:42 INFO:proxy:Received request: GET api/v1/me/trial_status
2024-06-12 16:58:42 INFO:proxy:Received request: GET https://backend.raycast.com/api/v1/me/trial_status
2024-06-12 16:58:42 INFO:proxy:Received request to /api/v1/me
2024-06-12 16:58:42 INFO:proxy:Received request: GET https://backend.raycast.com/api/v1/me
2024-06-12 16:58:42 INFO:proxy:Received request to /api/v1/ai/models
2024-06-12 16:58:42 INFO:proxy:Received request: GET https://backend.raycast.com/api/v1/ai/models
2024-06-12 16:58:52 INFO:     192.168.65.1:61920 - "GET /api/v1/me/trial_status HTTP/1.1" 500 Internal Server Error
2024-06-12 16:58:52 INFO:     192.168.65.1:61921 - "GET /api/v1/me HTTP/1.1" 500 Internal Server Error
2024-06-12 16:58:52 INFO:     192.168.65.1:61922 - "GET /api/v1/ai/models HTTP/1.1" 500 Internal Server Error
2024-06-12 16:58:55 INFO:     192.168.65.1:61923 - "POST /api/v1/translations HTTP/1.1" 500 Internal Server Error
2024-06-12 16:58:55 ERROR:    Exception in ASGI application
2024-06-12 16:58:55 Traceback (most recent call last):
2024-06-12 16:58:55   File "/project/app/main.py", line 533, in proxy_translations
2024-06-12 16:58:55     async for content in _get_bot(model_name).translate_completions(
2024-06-12 16:58:55   File "/project/app/main.py", line 471, in _get_bot
2024-06-12 16:58:55     return next(iter(MODELS_DICT.values()))
2024-06-12 16:58:55 StopIteration
2024-06-12 16:58:55 
2024-06-12 16:58:55 The above exception was the direct cause of the following exception:
2024-06-12 16:58:55 
2024-06-12 16:58:55 Traceback (most recent call last):
2024-06-12 16:58:55   File "/project/pkgs/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
2024-06-12 16:58:55     result = await app(  # type: ignore[func-returns-value]
2024-06-12 16:58:55   File "/project/pkgs/uvicorn/middleware/proxy_headers.py", line 78, in __call__
2024-06-12 16:58:55     return await self.app(scope, receive, send)
2024-06-12 16:58:55   File "/project/pkgs/fastapi/applications.py", line 276, in __call__
2024-06-12 16:58:55     await super().__call__(scope, receive, send)
2024-06-12 16:58:55   File "/project/pkgs/starlette/applications.py", line 122, in __call__
2024-06-12 16:58:55     await self.middleware_stack(scope, receive, send)
2024-06-12 16:58:55   File "/project/pkgs/starlette/middleware/errors.py", line 184, in __call__
2024-06-12 16:58:55     raise exc
2024-06-12 16:58:55   File "/project/pkgs/starlette/middleware/errors.py", line 162, in __call__
2024-06-12 16:58:55     await self.app(scope, receive, _send)
2024-06-12 16:58:55   File "/project/pkgs/starlette/middleware/exceptions.py", line 79, in __call__
2024-06-12 16:58:55     raise exc
2024-06-12 16:58:55   File "/project/pkgs/starlette/middleware/exceptions.py", line 68, in __call__
2024-06-12 16:58:55     await self.app(scope, receive, sender)
2024-06-12 16:58:55   File "/project/pkgs/fastapi/middleware/asyncexitstack.py", line 21, in __call__
2024-06-12 16:58:55     raise e
2024-06-12 16:58:55   File "/project/pkgs/fastapi/middleware/asyncexitstack.py", line 18, in __call__
2024-06-12 16:58:55     await self.app(scope, receive, send)
2024-06-12 16:58:55   File "/project/pkgs/starlette/routing.py", line 718, in __call__
2024-06-12 16:58:55     await route.handle(scope, receive, send)
2024-06-12 16:58:55   File "/project/pkgs/starlette/routing.py", line 276, in handle
2024-06-12 16:58:55     await self.app(scope, receive, send)
2024-06-12 16:58:55   File "/project/pkgs/starlette/routing.py", line 66, in app
2024-06-12 16:58:55     response = await func(request)
2024-06-12 16:58:55   File "/project/pkgs/fastapi/routing.py", line 237, in app
2024-06-12 16:58:55     raw_response = await run_endpoint_function(
2024-06-12 16:58:55   File "/project/pkgs/fastapi/routing.py", line 163, in run_endpoint_function
2024-06-12 16:58:55     return await dependant.call(**values)
2024-06-12 16:58:55 RuntimeError: coroutine raised StopIteration

**Comment by yufeikang** [comment]
Hey there! 🎉 Could you please give the latest version a try? Thanks a lot!
